# Menggunakan image Nginx versi terbaru dari Docker Hub
FROM nginx:alpine

# Menyalin file HTML ke direktori default Nginx di dalam kontainer
COPY index.html /usr/share/nginx/html/

# Menentukan port yang akan digunakan oleh server Nginx
EXPOSE 80
